name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '54 2 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          days-before-stale: 120
          days-before-close: 60
          stale-issue-message: 'This issue is stale because it has had no activity for 60 days. It will be closed after 14 more days of no activity.'
          stale-pr-message: 'This pull request is stale because it has had no activity for 60 days. It will be closed after 14 more days of no activity.'
